#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# This wizard provisions the GitHub CLI (`gh`) on this Windows box, per the
# scope agreed with the user:
#   1. install gh            → winget, per-user (no admin needed)
#   2. fix PATH              → the per-user install is a portable zip; verify/repair PATH
#   3. verify install        → gh --version in a fresh shell
#   4. authenticate          → reuse the existing Credential Manager token
#   5. verify + smoke test   → gh auth status, then gh issue list in this repo
#
# Machine facts this wizard is written against (probed 2026-09, Windows 10.0.26100,
# AMD64, non-admin shell — every one of these was measured, not assumed):
#   • gh NOT installed; no gh.exe in Program Files or LOCALAPPDATA\Programs.
#   • winget v1.29.380 present; `GitHub.cli` resolves to 2.101.0.
#   • For x64, winget's manifest carries TWO installers (see
#     manifests/g/GitHub/cli/2.101.0/GitHub.cli.installer.yaml in winget-pkgs):
#       – InstallerType: wix, Scope: machine  → gh_2.101.0_windows_amd64.msi,
#         DefaultInstallLocation %ProgramFiles%/GitHub CLI. Needs administrator.
#       – InstallerType: zip, NestedInstallerType: portable (no Scope → user)
#         → gh_2.101.0_windows_amd64.zip, NestedInstallerFiles bin/gh.exe.
#     Passing `--scope user` therefore selects the PORTABLE ZIP, which is the
#     whole reason this wizard can install without admin rights. The MSI would
#     need elevation. That choice drives stage 2: a portable install does NOT
#     patch PATH the way the MSI does, so we must verify and repair it.
#   • Portables land under
#     %LOCALAPPDATA%\Microsoft\WinGet\Packages\GitHub.cli_*_8wekyb3d8bbwe\
#     — note the manifest's NestedInstallerFiles says bin/gh.exe, so the exe
#     may sit one directory deeper than the package root. Stage 2 searches
#     recursively rather than guessing the depth.
#   • %APPDATA%\GitHub CLI\ already holds config.yml + hosts.yml (account
#     qiqqqqq517) from an earlier install, but hosts.yml carries NO oauth_token
#     — so the config survives while the login does not. Stage 4 must re-auth.
#   • Credential Manager holds a live 40-char gho_ token for github.com as
#     qiqqqqq517, with scopes repo / read:org / gist (plus gist, notifications,
#     read:gpg_key, user, workflow, write:public_key). Those first three are
#     exactly `gh auth login --with-token`'s documented minimum, so stage 4 can
#     run non-interactively — no browser OAuth device flow required.
#   • No WSL distro is installed (`wsl -l -q` is empty), so this runs under
#     Git Bash. The library's open_url still works here: ../Windows/explorer.exe
#     resolves on Git Bash's PATH (verified).
#   • PowerShell 7 (`pwsh`) is NOT installed on this box — only Windows
#     PowerShell 5.1 (`powershell.exe`). Stage 2 must therefore call the latter;
#     the `_ps` helper below picks whichever exists.
#
# Nothing secret is written to disk by this wizard: the token goes straight
# into gh's own credential store. No .env keys, no GitHub Actions secrets —
# this repo's CI does not consume gh credentials (releases go out via the
# REST API per AGENTS.md, and workflows are disabled by policy).

TOTAL_STAGES=5

# _ps "snippet" — run a one-off PowerShell snippet, preferring pwsh 7 but
# falling back to Windows PowerShell 5.1 (`powershell.exe`), which is the only
# one present on this machine. Returns 127 if neither exists.
_ps() {
  if command -v pwsh >/dev/null 2>&1; then
    pwsh -NoProfile -NonInteractive -Command "$1"
  elif command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -NoProfile -NonInteractive -Command "$1"
  else
    return 127
  fi
}

banner "GitHub CLI (gh) setup"

# ── Stage 1: install gh ───────────────────────────────────────────────────
stage "Install gh via winget"
say "We'll install the GitHub CLI from the official winget package."
note "Official docs: https://cli.github.com/  (winget id: GitHub.cli)"
open_url "https://cli.github.com/"
echo
note "Package details (first lines of 'winget show'):"
winget show --id GitHub.cli --source winget --accept-source-agreements 2>/dev/null \
  | head -n 8 | sed 's/^/    /' || true
echo
# Be explicit about WHY --scope user, because the same package id means two
# very different installs depending on the flag.
note "winget publishes two x64 installers for this package: a machine-wide MSI"
note "(needs administrator) and a portable zip (per-user, no admin). Passing"
note "--scope user selects the portable zip — that's why no elevation is needed."
echo
if confirm "Install GitHub CLI now?"; then
  # --accept-package-agreements / --accept-source-agreements: unattended.
  if winget install --id GitHub.cli --source winget --scope user \
       --accept-package-agreements --accept-source-agreements; then
    say "${GREEN}gh installed.${RESET}"
  else
    warn "winget returned a non-zero exit."
    note "Common causes: gh is already installed and current (harmless), or the"
    note "per-user installer wasn't applicable."
    if confirm "Retry without --scope user? (this may select the machine-wide MSI and raise a UAC prompt)"; then
      if winget install --id GitHub.cli --source winget \
           --accept-package-agreements --accept-source-agreements; then
        say "${GREEN}gh installed.${RESET}"
      else
        SKIPPED+=("install gh — winget failed twice; install by hand from https://cli.github.com/")
        warn "Install still failed — see https://cli.github.com/ for the manual MSI link."
      fi
    else
      SKIPPED+=("confirm gh actually installed — winget did not report success")
    fi
  fi
else
  SKIPPED+=("install gh — you declined; run: winget install --id GitHub.cli --source winget --scope user")
  warn "skipped. The remaining stages need gh, so they will report what's missing."
fi

# ── Stage 2: PATH ─────────────────────────────────────────────────────────
# `--scope user` installs the PORTABLE zip, which does not wire PATH the way
# the MSI does. winget exposes portables by appending the package directory to
# the user PATH (that's how the Node package sits on PATH on this box), but
# that only reaches NEW shells — and on some builds winget instead relies on a
# symlink farm in %LOCALAPPDATA%\Microsoft\WinGet\Links, which is EMPTY and on
# no PATH on this machine. So don't assume: find gh.exe on disk, then check
# PATH and repair it.
stage "Make sure gh is on PATH"
GH_EXE=""

# Resolve the winget packages root into MSYS form FIRST. $LOCALAPPDATA arrives
# from Windows as `C:\Users\...` (backslashes), and handing that mixed-separator
# shape to test/find is unreliable — so normalise before touching it.
WINGET_PKGS="${LOCALAPPDATA:-$USERPROFILE/AppData/Local}/Microsoft/WinGet/Packages"
WINGET_PKGS="${WINGET_PKGS//\\//}"
WINGET_PKGS=$(cygpath -u "$WINGET_PKGS" 2>/dev/null || printf '%s' "$WINGET_PKGS")

# The manifest declares NestedInstallerFiles bin/gh.exe, so the binary may sit
# below the package root — search recursively rather than guessing the depth.
if [[ -d "$WINGET_PKGS" ]]; then
  while IFS= read -r pkg; do
    [[ -n "$pkg" ]] || continue
    found=$(find "$pkg" -maxdepth 4 -iname 'gh.exe' -print -quit 2>/dev/null || true)
    if [[ -n "$found" ]]; then GH_EXE="$found"; break; fi
  done < <(find "$WINGET_PKGS" -maxdepth 1 -iname '*GitHub.cli*' -print 2>/dev/null || true)
fi

# Fallbacks: the machine-wide MSI location, plus user-scoped MSI locations in
# case a different installer was chosen. Only consulted if the search failed.
if [[ -z "$GH_EXE" ]]; then
  for candidate in \
    "/c/Program Files/GitHub CLI/gh.exe" \
    "$LOCALAPPDATA/Programs/GitHub CLI/gh.exe" \
    "$LOCALAPPDATA/Programs/gh/bin/gh.exe" ; do
    if [[ -f "$candidate" ]]; then GH_EXE="$candidate"; break; fi
  done
fi

# Normalise to a pure MSYS path. $LOCALAPPDATA arrives from Windows as
# `C:\Users\...` (backslashes), so globbing over it yields a mixed-separator
# path that `dirname` mangles and that breaks PATH resolution when prepended
# raw. Convert the separators first, then let cygpath do the real translation.
if [[ -n "$GH_EXE" ]]; then
  GH_EXE="${GH_EXE//\\//}"
  GH_EXE=$(cygpath -u "$GH_EXE" 2>/dev/null || printf '%s' "$GH_EXE")
fi

if [[ -n "$GH_EXE" && -f "$GH_EXE" ]]; then
  say "Found gh at: $GH_EXE"
  GH_DIR_WIN=$(cygpath -w "$(dirname "$GH_EXE")" 2>/dev/null || dirname "$GH_EXE")
  note "Its directory: $GH_DIR_WIN"

  if command -v gh >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} gh is already resolvable on PATH — nothing to do."
    note "($(command -v gh))"
  else
    warn "gh.exe exists but is NOT on this shell's PATH."
    note "That is expected in the shell that ran the install — PATH changes only"
    note "reach NEW shells. Adding it to your persistent user PATH so it works"
    note "everywhere from now on."
    if confirm "Add $GH_DIR_WIN to your persistent user PATH?"; then
      # Update the USER PATH through .NET. Deliberately NOT setx: it truncates
      # at 1024 characters and would corrupt this machine's already-long PATH
      # (user PATH is 626 chars, machine PATH 1733). The directory is handed
      # over in an environment variable, so spaces or quotes in it cannot break
      # the quoting. Uses _ps, since pwsh 7 is not installed here.
      export GH_DIR_FOR_PS="$GH_DIR_WIN"
      if _ps '[Environment]::SetEnvironmentVariable("Path", (((([Environment]::GetEnvironmentVariable("Path","User")) -split ";") | Where-Object { $_ -ne "" -and $_ -ne $env:GH_DIR_FOR_PS }) + $env:GH_DIR_FOR_PS) -join ";", "User")'; then
        say "${GREEN}✓${RESET} added to your persistent user PATH."
        note "(The directory was appended last, so nothing existing was reordered.)"
      else
        warn "could not update PATH automatically — add it by hand: $GH_DIR_WIN"
        SKIPPED+=("add $GH_DIR_WIN to PATH by hand")
      fi
      unset GH_DIR_FOR_PS
    else
      SKIPPED+=("add $GH_DIR_WIN to PATH — gh won't resolve in new shells until you do")
    fi
  fi
else
  warn "Couldn't find gh.exe on disk — stage 1 probably didn't complete."
  SKIPPED+=("locate gh.exe — install gh first (winget install --id GitHub.cli --source winget --scope user)")
fi

# Make gh usable for the REMAINING stages of this run. The persistent PATH set
# above only helps future shells, so prepend the directory in-process too —
# otherwise stage 5 would spuriously fail on a machine that is actually fine.
if [[ -n "$GH_EXE" ]]; then
  GH_DIR_MSYS=$(dirname "$GH_EXE")
  if [[ -d "$GH_DIR_MSYS" ]]; then
    PATH="$GH_DIR_MSYS:$PATH"
    export PATH
  fi
fi

# ── Stage 3: verify the install ───────────────────────────────────────────
stage "Verify the install"
if command -v gh >/dev/null 2>&1; then
  say "gh resolves to: $(command -v gh)"
  echo
  gh --version | sed 's/^/    /'
  echo
  say "${GREEN}✓${RESET} gh is installed and runs."
  note "If a NEW Windows Terminal window still can't find gh, close it fully and"
  note "reopen — a new *tab* inherits the old environment; a new *window* doesn't."
else
  warn "gh still isn't resolvable."
  SKIPPED+=("gh not on PATH — open a NEW Windows Terminal window and re-check: gh --version")
fi
pause "Press Enter once you're happy with the version above."

# ── Stage 4: authenticate ─────────────────────────────────────────────────
# gh needs `repo`, `read:org`, `gist`. This box already has such a token in
# Windows Credential Manager (used by git and by the release runbook), so we
# reuse it instead of making you walk the browser OAuth device flow.
stage "Authenticate gh"
if ! command -v gh >/dev/null 2>&1; then
  warn "Skipping — gh isn't runnable (see stage 3)."
  SKIPPED+=("authenticate gh — install it first, then run: gh auth login")
else
  if gh auth status >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} gh is already authenticated:"
    gh auth status 2>&1 | sed 's/^/    /'
  else
    say "gh isn't authenticated yet. Two ways to fix that:"
    echo
    step "Option A — reuse the GitHub token already stored in Windows Credential"
    note "           Manager (this box has one for github.com / qiqqqqq517)."
    note "           Faster, no browser, and it stores the token in gh's own"
    note "           credential store — never in a file, never echoed to screen."
    step "Option B — open a browser and do the normal OAuth device-code login."
    echo
    note "If you'd rather log in as a different GitHub account, choose B."
    echo
    if confirm "Use Option A — reuse the existing stored token?"; then
      # Pull the token out of Credential Manager via git's credential helper.
      # Read it through a pipe so it never lands in argv (visible in process
      # listings) and never touches disk.
      say "Reading the stored token from Credential Manager…"
      TOKEN=""
      TOKEN=$(printf 'protocol=https\nhost=github.com\n\n' \
        | git credential fill 2>/dev/null \
        | sed -n 's/^password=//p' | head -n1) || true

      if [[ -z "$TOKEN" ]]; then
        warn "No stored token found for github.com."
        note "Falling back to the browser flow. gh will show a one-time code —"
        note "copy it, press Enter here, then paste it in the browser."
        open_url "https://github.com/login/device"
        gh auth login --hostname github.com --git-protocol https --web \
          || SKIPPED+=("gh auth login — browser flow didn't complete; re-run: gh auth login")
      else
        say "Got a token (${#TOKEN} characters). Handing it to gh…"
        if printf '%s\n' "$TOKEN" | gh auth login --hostname github.com \
             --git-protocol https --with-token; then
          say "${GREEN}✓${RESET} gh authenticated."
        else
          warn "gh rejected the token. Its scopes may have changed, or it expired."
          note "Falling back to the browser flow…"
          open_url "https://github.com/login/device"
          gh auth login --hostname github.com --git-protocol https --web \
            || SKIPPED+=("gh auth login — browser flow didn't complete; re-run: gh auth login")
        fi
        unset TOKEN
      fi

      # gh's git operations need a credential helper of their own. `gh auth
      # setup-git` wires that up so `git push` over https uses gh's token.
      if gh auth status >/dev/null 2>&1; then
        note "Configuring git to use gh as its credential helper…"
        gh auth setup-git --hostname github.com \
          && say "${GREEN}✓${RESET} git credential helper configured." \
          || warn "gh auth setup-git failed — git will keep using its own helper."
      fi
    else
      say "Opening the browser flow."
      open_url "https://github.com/login/device"
      gh auth login --hostname github.com --git-protocol https --web \
        || SKIPPED+=("gh auth login — browser flow didn't complete; re-run: gh auth login")
    fi
  fi
fi

# ── Stage 5: verify auth + smoke test ─────────────────────────────────────
stage "Verify authentication"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  echo
  gh auth status 2>&1 | sed 's/^/    /'
  echo
  say "Now a real API call against this repo, to prove the token's scopes are"
  say "sufficient (an auth status can pass while scopes are still too narrow)."
  echo
  if gh issue list --limit 5 2>/dev/null; then
    echo
    say "${GREEN}✓${RESET} gh is installed, authenticated, and talking to GitHub."
  else
    warn "Authenticated, but the API call failed."
    note "If you saw a scope error, refresh the token's scopes:"
    note "  gh auth refresh -h github.com -s repo,read:org,gist"
    SKIPPED+=("verify API access — run: gh auth refresh -h github.com -s repo,read:org,gist")
  fi
  echo
  note "Handy: the issue-tracker flow in docs/agents/issue-tracker.md now works."
  note "gh can also install agent skills (manual: cli.github.com/manual/gh_skill):"
  note "  gh skill install <owner>/<repo> [<skill>] --scope user"
  note "  browse what's available first with: gh skill search"
else
  warn "gh isn't installed and authenticated, so there's nothing to verify."
  SKIPPED+=("verify gh — install and authenticate it, then run: gh auth status")
fi

finish