name: Gradle Dependency Submission
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  submit-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ========== 手动指定JDK核心代码 ==========
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'      # 修改这里：8 /11 /17 /21
          distribution: 'temurin' # 推荐temurin（Adoptium），也可以用 microsoft
      # =======================================

      # 提交依赖图
      - name: Submit Gradle dependencies
        uses: gradle/actions/dependency-submission@v4
